config/routes.rb
PortableDyno::Application.routes.draw do

  resources :tweets


  # public routes
  root :to => 'home#index'
  get '/contact' => 'home#contact'
  get '/faq' => 'home#faq'
  get '/about' => 'home#about'
  get '/gallery' => 'home#gallery'
  
  # admin only routes
  match 'admin' => 'admin#index'
  devise_for :users, :skip => [:registrations]
    as :user do # only use the registration routes we need
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  scope '/admin' do # scope the user admin pages so they don't conflict with devise
    resources :users
  end
  resources :events

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :send_at, :sent
  belongs_to :tweet
  validates :sent_at, :presence => true
  
  # processes the tweet
  def deliver
    #TODO
  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_many :tweets, :dependent => :destroy
  
  scope :future_published_events, lambda { where('publish = 1 AND event_start_date >= ?', self.get_today_at_midnight) }
  
  attr_accessible :name, :description, :event_start_date, :event_start_date_time, :event_end_date, 
    :event_end_date_time, :location, :address1, :address2, :city, :country, :state, :zipcode, :publish
  
  validates :name, :event_start_date, :location, :presence => true 
  
  
  # Valiation notes:
  # trust that date and times are in the correct format
  # trust that the app whitelists the text fields
  # don't validate zipcode in case this is in a different country 
  #   we may not even use zipcode until location is broken out into it's own model
  #   even then we may only need to worry about Mexico and Canada 
  #   we'll worry about fr_ca localization at that time
  
  #TODO:  UI Validation start date must be <= end date
  #  if end time is given, start time must be provided and must be before end date
  # start date should be today or in the future - will we ever backfill?  maybe?
  
  def self.get_today_at_midnight
    current = DateTime.now
    midnight = Date.new(current.year, current.month, current.day)
  end
   
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :event_id, :message
  belongs_to :event
  has_many :deliveries
  
  validates :message, :presence => true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    admin_path
  end
  
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @events = Event.order('event_start_date, event_start_date_time').all
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to events_path, :notice => 'Event was successfully created.'
    else
      render :new 
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to events_path, :notice => 'Event was successfully updated.'
    else
      render :edit 
    end
  end
  
  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to events_path
  end
  
  #TODO add a preview event feature before publishing
  def preview
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @events = Event.future_published_events
    render :layout => 'home_index'
  end

  def contact
    @marquee_title = 'Schedule an Event'
  end

  def faq
    @marquee_title = 'Frequently Asked Questions'
  end
  
  def about
    @marquee_title = 'About Our Dyno'
  end
  
  def gallery
    @marquee_title = 'Gallery'
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def create
    @tweet = Tweet.new(params[:tweet])
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update_attributes(params[:tweet])
      format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
    else
      format.html { render action: "edit" }
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :ensure_admin
  
  def index
    @users = User.order('email')
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => 'User was successfully created.'
    else
      render :new 
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => 'User was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    user = User.find(params[:id])
    unless current_user == user
      user.destroy
      redirect_to users_path
    else
      redirect_to users_path, :notice => 'You cannot delete yourself.  That would be bad.'
    end
  end
  
  private
  
  def ensure_admin
    unless current_user.admin?
      flash[:error] = 'You are not authorized to edit users.'
      redirect_to admin_path
    end 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_error_messages(resource)
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "Errors when saving"
    
    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML
    
    html.html_safe
  end
  
end

app/helpers/events_helper.rb
module EventsHelper

  def get_time(time)
    time.nil? ? nil : I18n.l(time, :format => :short)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/admin/index.html.erb
<h1>Portable-Dyno Administration</h1>

<%= link_to 'Logout', destroy_user_session_path, :method => :delete %><br>
<%= link_to 'Edit My Info', edit_user_registration_path %><br>
<% if current_user.admin? %>
    <%= link_to "User Administration", users_path %><br>
<% end %>
<%= link_to "Events", events_path %><br>
TODO:  link to image galleries<br>
TODO:  link to customers<br>
TODO:  link to locations<br>

app/views/events/_event.html.erb
<li><%= event.name %> - <%= event.event_start_date %>
    <%= link_to "Edit", edit_event_path(event) %> 
    <%= link_to "Delete", event_path(event), :method => :delete, :confirm => "Are you sure you want to delete this event?" %>
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= display_error_messages(@event) %>
  <div>
    <%= f.label :name %><br/>
    <%= f.text_field :name, :autofocus => true %>
  </div>
  <div class="when">
    <div>
      <%= f.label :event_start_date %><br/>
      <%= f.text_field :event_start_date, :type => 'date' %>
    </div>
    <div>
      <%= f.label :event_start_date_time %><br/>
      <input id="event_event_start_date_time" name="event[event_start_date_time]" type="time" value="<%= get_time(@event.event_start_date_time) %>">
    </div>
    <div>
      <%= f.label :event_end_date %><br/>
      <%= f.text_field :event_end_date, :type => 'date' %>
    </div>
    <div>
      <%= f.label :event_end_date_time %><br/>
      <input id="event_event_end_date_time" name="event[event_end_date_time]" type="time" value="<%= get_time(@event.event_end_date_time) %>">
    </div>
  </div>
  <div class="description">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
  <div class="location">
    <div>
      <%= f.label :location %><br/>
      <%= f.text_field :location %>
    </div>
    <div>
      <%= f.label :address1 %><br/>
      <%= f.text_field :address1 %>
    </div>
    <div>
      <%= f.label :address2 %><br/>
      <%= f.text_field :address2 %>
    </div>
    <div>
      <%= f.label :city %><br/>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :state %> (US Only)<br/>
      <%= f.select :state, options_for_select([["Select a State", ""]] + US_STATES, @event.state) %>
    </div>
    <div>
      <%= f.label :zipcode %><br/>
      <%= f.text_field :zipcode, :size => 10 %>
    </div>
    <div>
      <%= f.label :country %><br/>
      <%= f.country_select :country, ['United States'] %>    
    </div>
  </div>
  <div>
    <%= f.label :publish %><br/>
    <%= f.check_box :publish %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/events/edit.html.erb
<h1>Event Edit</h1>
<%= render 'form' %>
<%= link_to "Event List", events_path %>

app/views/events/index.html.erb
<h1>Listing all Events</h1>

<%= link_to "New Event", new_event_path %><br/>
<ul>
<%= render @events %>
</ul>
<%= link_to "Administration Home", admin_path %>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>
<%= link_to "Event List", events_path %>

app/views/home/_contact_us.html.erb
<div class="inset">
    <h2>What can we do for you?</h2>
    <form action="mailer.php" method="post" class="contact">
        <label>Name: </label>
        <input type="text" name="nam" class="name_input">
        <label>Company: </label>
        <input type="text" name="dukan" class="company_input">
        <label>Phone: </label>
        <input type="text" name="fon" class="phone_input">
        <label>Email: </label>
        <input type="text" name="dak" class="email_input">
        <span class="hidden">
            <label>Please leave this line blank: </label>
            <input type="text" name="name">
        </span>
        <label>Message: </label>
        <textarea name="message" rows="12" cols="30" class="message_input"></textarea>
        <input type="submit" name="submit" value="Submit"  class="submit_input">
        <div class="row"></div>
    </form>
</div>

app/views/home/_event.html.erb
<div class="event">
    <em><%= event.name %></em><br/>
    Start Date:  <%= l(event.event_start_date, :format => :long) %> - <%= l(event.event_start_date_time, :format => :pretty) %><br/>
    <% unless event.event_end_date.blank? %>
        End Date:  <%= l(event.event_end_date, :format => :long) %> - <%= l(event.event_end_date_time, :format => :pretty) %><br/>
    <% end %>
    Location:  <%= event.location %> <br/>
    Address:  <%= event.address1 %>, 
    <% unless event.address2.blank? %> <%= event.address2 %>,<% end %> 
    <%= event.city %>, 
    <% unless event.state.blank? %><%= event.state %>,<% end %>
    <%= event.country %><br/>
    <br/>
</div>

app/views/home/_footer.html.erb
<div class="row footer small">
    &copy;2011-<%= DateTime.now.year %> Portable-Dyno<br>
    <%= PHONE %><br>
    <%= link_to 'Contact', contact_path %> : <%= link_to 'About', about_path %> : <%= link_to 'FAQ', faq_path %> : <%= link_to 'Gallery', gallery_path %>
</div>
<div class="row"></div>

app/views/home/_header.html.erb
<div class="row">
    <%= link_to root_path do %>
        <div class="inside_marquee">
            <h1>Portable Dyno</h1>
        </div>
    <% end %>
    <div class="marquee_id">
        <h2><%= @marquee_title %></h2>
    </div>
    <div class="inside_number"><%= PHONE %></div>
</div>

app/views/home/about.html.erb
<div class="b10column box">
    <h2>Dyno Dynamics 450DS eddy current steady state single axle chassis dynamometer.  
        More than just horsepower and torque readings
    </h2>
    <p>Traditional inertia style dynos were designed to reliably measure horsepower and torque.  
       Using such equipment would allow the tuner to try different modifications on engines 
       and subsequent systems and see direct results with varied accuracy.
    </p>
    <p>With an <a href="http://en.wikipedia.org/wiki/Dynamometer#Eddy_current_type_absorber">
       eddy current steady state dyno</a>, the tuning features have broadened.
    </p>   
    <p>Steady state tuning-  You can have the dyno hold your car at any RPM.  This 
             comes in VERY handy when setting up a new fuel map on an after market ECU.  
             Set the dyno at the desired RPM in conjunction with the real time wide band AFR 
             lambda sensor and you can step tune your car all the way up the RPM spectrum to the 
             desired stoichiometric value safely and reliably.
    </p>
    <p>Engine and drive train break in-  When you bolt up that new engine to your new gear box and drive 
            line it's very difficult to stay under the revs until it's properly broken in.  How many times have 
            you been out for a short easy ride only to stop at a red light and have that other brand car pull 
            up next to you wanting to have a go.  With the eddy current dyno you can set the load, ramp up and ramp 
            down speed parameters to safely break in your engine under real world load simulation's without going 
            over the desired revs until everything's seated itself properly.  Also having the ability to safely 
            walk around the front of the car and check for any leaks or loose fittings under the hood while the 
            car is going 50mph is a spiffy feature not easily achieved without a dyno.
    </p>
    <p>Like an elephant-  The dyno saves all customer runs.  So you install some headers and an intake this year and 
            have your car dyno'ed.  Then over the winter you install that huge exhaust, cam, massive CFM carb or a super 
            charger.  When you dyno the car again we can pull up your previous runs and overlay them for comparison's 
            sake and see how you've done.  You'd be surprised how many modifications end up hurting performance 
            rather than improving it.
    </p>
    <br>
    <h2>Now for some features</h2>    
    <b>Ideal for diagnosis and performance work on the following:</b>
    <ol><li>Rear wheel drive</li>
        <li>Front wheel drive</li>
        <li>4WD/AWD cars, recreational vehicles (with selectable single axle drive)</li>
        <li>Race cars</li>
        <li>Sport utility vehicles</li>
        <li>Motor Cycles</li>
        <li>Light commercial vehicles under 9,900 lb</li>
    </ol>
    <b>Real time high resolution graphing including:</b>
    <ol><li>Horsepower</li>
        <li>Tractive Effort</li>
        <li>Torque</li>
        <li>Air:Fuel ratio</li>
        <li>Lambda</li>
        <li>Vacuum/Boost</li>
    </ol>   
    <p><b>High Speed AFR</b><br>
       Live monitoring of Air:Fuel ratio/Lambda and Vacuum/Boost.
    </p>
    <p><b>Constant Speed Mode</b><br>
       Dial in the speed you want.
    </p>
    <p><b>Constant Load Mode</b><br>
       Dial in the load you want.
    </p>
    <p><b>Variable Ramp Rate</b><br>
        Ramp Up-Hold-Down.  Dial in the desired acceleration.
    </p>
</div>

app/views/home/contact.html.erb
<div class="box b7column">
    <p>Our Dyno Dynamics 450 single axle portable dyno can be used with rear wheel drive, 
       front wheel drive, race cars, sports utility vehicles, go-karts, light commercial vehicles 
       "under 9900lbs" and motorcycles.
    </p>
    <br>
    <p><b>We're accepting submissions for the <%= DateTime.now.year %> season!<br><br>
          Please use the form to the right or call us at <%= PHONE %> for availability.
    </p>
</div>
<div class="box b5column">
    <%= render 'contact_us' %>
</div>
        

app/views/home/faq.html.erb
<div class="b5column box">
    <div class="inset faq_key">
        <ul><li><a href="#faq1">Who drives the car for the test?</a></li>
            <li><a href="#faq2">What does it measure?</a></li>
            <li><a href="#faq3">Why do a dyno run?</a></li>
            <li><a href="#faq4">How much does it cost?</a></li>
            <li><a href="#faq5">Can I make adjustments to see impact?</a></li>
            <li><a href="#faq6">Will you make adjustments to see impact?</a></li>
            <li><a href="#faq7">Can it damage my engine?</a></li>
            <li><a href="#faq8">Do you redline the engine?</a></li>
            <li><a href="#faq9">Who is responsible if something breaks during the test?</a></li>
            <li><a href="#faq10">I just installed a new 800hp engine, can you break it in for me?</a></li>
            <li><a href="#faq11">I have a large car collection, could you come to my facility and run each one?</a></li>
            <li><a href="#faq12">Can you do a dyno day for my club?</a></li>
            <li><a href="#faq13">Can you set up the dyno anywhere?</a></li>
            <li><a href="#faq14">What does the dyno need for power?</a></li>
        </ul>
    </div>
</div>
<div class="b7column box">
    <div class="faq">
        <p><a name="faq1">Who drives the car for the test?</a></p>
        <p>A factory trained dyno operator drives the car onto the dyno and runs the test.</p>
    </div>
    <div class="faq">
        <p><a name="faq2">What does it measure?</a></p>
        <p>The Dyno can measure the following:  
           Horsepower, torque, air/fuel ratio, boost, air intake temperature,
           fully integrated weather station measuring humidity, air temperature and isobaric pressure.
        </p>
    </div>
    <div class="faq">
        <p><a name="faq3">Why do a dyno run?</a></p>
        <p>To establish a baseline for your car or truck. Find out how much you've gained
            by adding that new air intake, headers, ECU flash or fuel injection.  You can also see 
            how your air/fuel ratio compares to your horsepower torque to make sure you've tuned 
            your car to its optimal efficiency.
        </p>
    </div>
    <div class="faq">
        <p><a name="faq4">How much does it cost?</a></p>
        <p>No two events or appointments are the same so "its best to email" or call for an accurate quote.</p>
    </div>
    <div class="faq">
        <p><a name="faq5">Can I make adjustments to see impact?</a></p>
        <p>Adjustments should be done with a scheduled tuning appointment, that way we can focus on just your car.</p>
    </div>
    <div class="faq">
        <p><a name="faq6">Will you make adjustments to see impact?</a></p>
        <p>Only when scheduled for a tuning appointment. </p>
    </div>
    <div class="faq">
        <p><a name="faq7">Can it damage my engine?</a></p>
        <p>The eddy current steady state dyno simulates road like conditions.  If your car is in 
           good working order then it should be no different than taking a spirited drive through the countryside. 
        </p>
    </div>
    <div class="faq">
        <p><a name="faq8">Do you redline the engine?</a></p>
        <p>We ask the customer how far they'd like us to run up the RPMs. Typically we run it 
           up until it stops producing horsepower, which is about 1500 RPM below redline for most.
        </p>
    </div>
    <div class="faq">
         <p><a name="faq9">Who is responsible if something breaks during the test?</a></p>
         <p>The dyno operator is not responsible for any damage to the automobile caused due to 
            engine or drive train failure.  Remember the dyno simulates real world conditions with 
            the vehicle accelerating to measure its performance.  You can specify a max RPM before the run begins.</p>
    </div>
    <div class="faq">
        <p><a name="faq10">I just installed a new 800hp engine, can you help break it in for me?</a></p>
        <p>Absolutely!  The steady state eddy current dyno can hold a specific speed, 
            load and ramp rate to maximize the ideal break in conditions for your specific motor and drive line.  
        </p>
    </div>
    <div class="faq">
        <p><a name="faq11">I have a large car collection, could you come to my facility and run each one?</a></p>
        <p>Absolutely!  We first warm up each car to optimal running temperature and then run a series
           of simulated driving conditions.  This ensures the car gets all fluids up to temp 
           and burns off any moisture in the engine and exhaust system.  Running your car on the dyno
           ensures no chipped paint, no risking accidents while driving on the road and minimal
           mileage on the car.  Upon request we also inspect all systems and report any 
           findings to your mechanic so when you take out the car it's 100% ready to go.
        </p>
    </div>
    <div class="faq">
        <p><a name="faq12">Can you do a dyno day for my club?</a></p>
        <p>Club events generally have a ten vehicle minimum.  All expectations and logistics 
           should be scheduled at least two weeks in advance.
        </p>
    </div>
    <div class="faq">
        <p><a name="faq13">Can you set up the dyno anywhere?</a></p>
        <p>The dyno requires a hard stable level surface to set up.  Concrete and asphalt 
           work best, but a one inch 4x12' steel plate or plywood will work in a pinch.
        </p>
    </div>
    <div class="faq">
         <p><a name="faq14">What does the dyno need for power?</a></p>
         <p>A 220V 60Htz power source should be available within 150' to 200'.  Generators can be 
            used if they produce an inverted 6000 Watt or higher pure sinewave powersource.  
            Email or call to confirm your site is suitable.
         </p>
    </div>
</div>

app/views/home/gallery.html.erb
<div class="b10column box">
    <p>Images from various events.</p>
    <ul><li><a href="ApexAuto/index.html">Apex Auto</li>
        <li><a href="Portland Motorclub Laborday Day 2011/index.html">Portland Motorclub Laborday Day 2011</li>
        <li><a href="Waterfest17/index.html">Waterfest 2011, NJ</a></li>
        <li><a href="Vacationland VW 8-7-2011/index.html">Vacationland VW 8-7-2011</a></li>
    </ul>
</div>

app/views/home/index.html.erb
<div class="content_well shadow">
    <div class="row">
        <div class="box b7column social_icons">
            <a href="http://www.facebook.com/pages/Portable-Dyno/174327369283538">
                <%= image_tag 'social_facebook.jpg', :alt => 'Portable-Dyno on Facebook' %>
            </a>
            <a href="http://twitter.com/portabledyno">
                <%= image_tag 'social_twitter.jpg', :alt => 'Portable-Dyno on Twitter' %>
            </a>
        </div>
        <div class="box b5column">
            <div class="big number">Call us at <%= PHONE %></div>
        </div>
    </div>
    <div class="marquee row">
        <h1>Portable Dyno</h1>
        <p>The most advanced portable dynamometer in the New England area.</p>
    </div>
    <div class="row full_width">
        <div class="box b7column">
            <div class="link_box">
                <h3><a href="dyno.html">About Our Dynamometer</a></h3>
                <p></p>
            </div>
            <div class="link_box">
                <h3><a href="faq.html">FAQ</a></h3>
                <p>Some answers to common questions.</p>
            </div>
            <div class="link_box">
                <h3><a href="pictures/index.html">Gallery</a></h3>
                <p></p>
            </div>
            <div class="link_box">
                <h3><a href="event.html">Schedule An Event!</a></h3>
                <p>You host the event, we'll bring the dyno!</p>
            </div>
            <div class="events_list">
                <% unless @events.empty? %>
                    <h2>Upcoming Events</h2>
                    <%= render :partial => 'home/event', :collection => @events %>
                <% end %>
            </div>
            <br>
            <br>
            <iframe width="425" height="349" src="http://www.youtube.com/embed/BG49o_sLZWQ?hl=en&fs=1" frameborder="0" allowfullscreen></iframe>
            <br>
            <br>       
        </div>
        <div class="box b5column">
            <%= render 'contact_us' %>
        </div>
        <%= render 'footer' %>
    </div>
</div>

app/views/home/thank_you.html.erb
<div class="b10column box">
    <p>Thank you for contacting us! We'll be getting back to you as soon as possible.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortableDyno</title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Portable Dynamometer</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/gif" href="<%= asset_path('favicon.gif') %>">
    <link rel="apple-touch-icon" href="<%= asset_path('touch_icon.jpg')%>
    <meta NAME="Description" CONTENT="Portable Dyno, Mobile Chassis Dyno, Dyno Rental, Mobile Dyno, Dyno Days: serving Maine, New Hampshire, Connecticut, Rhode Island, Massachusetts, and Vermont">
    <meta http-equiv="Content-Type" CONTENT="text/html; charset=iso-8859-1">
    <meta content='dyno, dynamometer, Portable Chassis Dyno, horsepower, portable, cars, automotive' name='keywords'>
    <meta content='Portable Dynamometer' name='title'>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "google_analytics" %>
</body>
</html>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.message %></td>
    <td><%= tweet.event_id %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Event:</b>
  <%= @tweet.event_id %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= display_error_messages(@user) %>
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, :autofocus => true %>
  </div>
  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_user.html.erb
<li><%= user.email %> 
    <%= link_to "Edit", edit_user_path(user) %> 
    <%= link_to "Delete", user_path(user), :method => :delete, :confirm => "Are you sure you want to delete this user?" %>
</li>

app/views/users/index.html.erb
<h1>Listing all Portable Dyno Users</h1>

<%= link_to "New User", new_user_path %><br/>
<ul>
<%= render @users %>
</ul>
<%= link_to "Administration Home", admin_path %>